'use client';
import type { Availability } from '@/lib/therapists/schema';
const days=['ראשון','שני','שלישי','רביעי','חמישי','שישי','שבת'];
const time=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
const minutes=(s:string)=>{const [h,m]=s.split(':').map(Number);return h*60+m;};
export default function AvailabilityEditor({value,onChange}:{value:Availability;onChange:(v:Availability)=>void}){
 return <fieldset className="space-y-3 border rounded-lg p-4"><legend className="font-bold px-2">שעות עבודה וחופשות · שעון ישראל</legend><p className="text-sm text-slate-500">להפסקה, הוסיפו שני טווחי שעות לאותו יום. שינוי שעות אינו מבטל תורים קיימים.</p>
 {value.hours.map((h,i)=><div key={i} className="flex flex-wrap gap-2 items-end"><label>יום<select className="input" value={h.day} onChange={e=>onChange({...value,hours:value.hours.map((x,j)=>j===i?{...x,day:Number(e.target.value)}:x)})}>{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label>משעה<input className="input" type="time" required value={time(h.start)} onChange={e=>onChange({...value,hours:value.hours.map((x,j)=>j===i?{...x,start:minutes(e.target.value)}:x)})}/></label><label>עד שעה<input className="input" type="time" required value={time(h.end)} onChange={e=>onChange({...value,hours:value.hours.map((x,j)=>j===i?{...x,end:minutes(e.target.value)}:x)})}/></label><button type="button" className="underline" onClick={()=>onChange({...value,hours:value.hours.filter((_,j)=>j!==i)})}>הסרת טווח</button></div>)}
 <button type="button" className="btn-secondary" onClick={()=>onChange({...value,hours:[...value.hours,{day:0,start:540,end:780}]})}>הוספת יום ושעות</button>
 <h3 className="font-bold">חופשות / ימים ללא קבלה</h3>{value.leave_dates.map((l,i)=><div key={i} className="flex gap-2 flex-wrap"><label>מתאריך<input className="input" type="date" required value={l.start} onChange={e=>onChange({...value,leave_dates:value.leave_dates.map((x,j)=>j===i?{...x,start:e.target.value}:x)})}/></label><label>עד תאריך<input className="input" type="date" required value={l.end} onChange={e=>onChange({...value,leave_dates:value.leave_dates.map((x,j)=>j===i?{...x,end:e.target.value}:x)})}/></label><button type="button" className="underline" onClick={()=>onChange({...value,leave_dates:value.leave_dates.filter((_,j)=>j!==i)})}>הסרה</button></div>)}<button type="button" className="btn-ghost" onClick={()=>onChange({...value,leave_dates:[...value.leave_dates,{start:'',end:''}]})}>הוספת חופשה</button></fieldset>;
}
