'use client';
import {useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {labels,treatments} from '@/lib/treatments/schema';
import AvailabilityEditor from './AvailabilityEditor';
import {availabilitySchema,type Therapist} from '@/lib/therapists/schema';
const fresh={name:'',email:'',treatments:[] as string[],active:true,duration:60,hours:[],leave_dates:[]};
export default function Manager({profiles}:{profiles:Omit<Therapist,'token_version'>[]}){
 const router=useRouter(),[editing,setEditing]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[link,setLink]=useState('');
 async function send(body:unknown){setBusy(true);setMessage('');setLink('');try{const r=await fetch('/api/admin/therapists',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error==='save_failed'?'לא ניתן לשמור. בדקו שאין מטפל נוסף עם אותו מייל.':d.error==='expired'?'הקישור פג תוקף. לחצו על חידוש הקישור.':'לא ניתן לבצע את הפעולה. בדקו את השדות.');if(d.link)setLink(d.link);setMessage(d.mail?(d.mail==='accepted'?'המייל נשלח.':d.mail==='not_configured'?'שליחת מיילים אינה מוגדרת. אפשר להעתיק את הקישור ולשלוח אותו ידנית.':'אין אישור לשליחת המייל. אל תשלחו שוב לפני בדיקה.'):'הפעולה נשמרה בהצלחה.');if(d.saved)setEditing(null);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'אירעה שגיאה');}finally{setBusy(false);}}
 function save(e:FormEvent){e.preventDefault();if(!availabilitySchema.safeParse({hours:editing.hours,leave_dates:editing.leave_dates}).success){setMessage('בדקו ששעות העבודה והחופשות תקינות ושאין טווחים חופפים.');return;}void send({action:'save',profile:editing});}
 return <div className="space-y-5"><button className="btn-primary" onClick={()=>setEditing({...fresh})}>הוספת מטפל/ת</button>{editing&&<form className="card space-y-4" onSubmit={save}><h2 className="font-bold">פרטי המטפל/ת</h2><fieldset disabled={busy} className="space-y-4"><label className="block">שם מלא<input className="input" value={editing.name} minLength={2} maxLength={100} required onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label className="block">מייל — אליו יישלחו הקישורים וההתראות<input className="input" type="email" dir="ltr" required value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/></label><div className="flex flex-wrap gap-4">{treatments.map((v,i)=><label key={v}><input type="checkbox" checked={editing.treatments.includes(v)} onChange={e=>setEditing({...editing,treatments:e.target.checked?[...editing.treatments,v]:editing.treatments.filter((t:string)=>t!==v)})}/> {labels.he[i]}</label>)}</div><label className="block">משך מפגש בדקות<input className="input" type="number" min={15} max={180} value={editing.duration} onChange={e=>setEditing({...editing,duration:Number(e.target.value)})}/></label><label><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/> מקבל/ת פניות חדשות</label><AvailabilityEditor value={editing} onChange={v=>setEditing({...editing,...v})}/><button className="btn-primary" disabled={!editing.treatments.length}>שמירת מטפל/ת</button><button type="button" className="btn-ghost" onClick={()=>setEditing(null)}>ביטול</button></fieldset></form>}
 <p role="status" className="text-teal-800">{message}</p>{link&&<div className="card"><label>קישור אישי — העתקה ידנית<input className="input" dir="ltr" value={link} readOnly onFocus={e=>e.target.select()}/></label><button className="btn-secondary" onClick={async()=>{try{await navigator.clipboard.writeText(link);setMessage('הקישור הועתק');}catch{setMessage('סמנו והעתיקו את הקישור מהשדה');}}}>העתקת הקישור</button></div>}
 {!profiles.length&&<p className="card">עדיין לא הוגדרו מטפלים. הוסיפו שם, מייל, תחום ושעות עבודה.</p>}{profiles.map(p=><article key={p.id} className="card space-y-3"><h2 className="text-xl font-bold">{p.name} · {p.active?'פעיל':'לא מקבל פניות'}</h2><p dir="ltr" className="text-right">{p.email}</p><p>{p.treatments.map(t=>labels.he[treatments.indexOf(t as any)]).join(' · ')} · {p.duration} דקות למפגש · {p.hours.length} טווחי עבודה</p><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setEditing({id:p.id,name:p.name,email:p.email,treatments:p.treatments,active:p.active,duration:p.duration,hours:p.hours,leave_dates:p.leave_dates})}>עריכת פרטים ושעות</button><button className="btn-ghost" disabled={busy||!p.active} onClick={()=>send({action:'link',id:p.id})}>קישור אישי</button><button className="btn-ghost" disabled={busy||!p.active} onClick={()=>send({action:'invite',id:p.id})}>שליחת הזמנה למייל</button><button className="underline" disabled={busy||!p.active} onClick={()=>{if(confirm('לחדש את הקישור? הקישור הישן יפסיק לעבוד.'))void send({action:'rotate',id:p.id});}}>חידוש וביטול הקישור הישן</button></div></article>)}</div>;
}
