'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
const states:Record<string,string>={none:'טרם נקבע סנכרון',pending:'ממתין לסנכרון',syncing:'מסנכרן',synced:'סונכרן ליומן Google',failed:'הסנכרון נכשל — ניתן לנסות שוב'};
export default function RequestControls({id,assigned,status,calendar}:{id:string;assigned:string|null;status:string;calendar:string}){
 const router=useRouter(),[matches,setMatches]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function send(action:string,extra={}){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/therapists',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,...extra})});const d=await r.json();if(!r.ok)throw new Error('הפעולה לא נשמרה. בדקו את מצב הפנייה והמטפל.');if(d.matches){setMatches(d.matches);if(!d.matches.length)setMessage('אין מטפל מתאים עם זמן פנוי ב־28 הימים הקרובים. הגדירו תחומים ושעות בניהול מטפלים.');}else{setMessage(d.mail?(d.mail==='accepted'?'הפנייה הוקצתה ונשלח מייל למטפל.':'הפנייה הוקצתה, אך אין אישור לשליחת מייל. ניתן לשלוח קישור ממסך ניהול מטפלים.'):d.calendar==='synced'?'סונכרן ליומן Google.':'הפעולה בוצעה. בדקו את מצב הסנכרון.');router.refresh();}}catch(e){setMessage(e instanceof Error?e.message:'אירעה שגיאה');}finally{setBusy(false);}}
 return <div className="rounded-lg bg-teal-50 p-3 space-y-3"><p>הקצאה: {assigned||'ממתין לבחירת מטפל'}</p>{['pending','contacted'].includes(status)&&<><button className="btn-secondary" disabled={busy} onClick={()=>send('match')}>מציאת מטפלים לפי תחום וזמינות</button>{matches.map(m=><button key={m.id} className="btn-ghost" disabled={busy} onClick={()=>send('assign',{therapistId:m.id})}>{m.name} — הקצאה ושליחת קישור</button>)}</>}<p>יומן: {states[calendar]??calendar}</p>{['pending','failed'].includes(calendar)&&<button className="underline" disabled={busy} onClick={()=>send('sync')}>ניסיון סנכרון ליומן</button>}<p role="status">{message}</p></div>;
}
