'use client';
import { useState, type FormEvent } from 'react';
import { localParts, localToUTC } from '@/lib/booking/schedule';
import {moxoDates,moxoHours} from '@/lib/moxo/schedule';
export default function ApproveRequest({id,approvedStart,duration=60}:{id:string;approvedStart?:string;duration?:number}){
 const [day,setDay]=useState('');const dates=moxoDates();
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),day=String(data.get('day')),time=String(data.get('time'));setBusy(true);
 try{const [h,m]=time.split(':').map(Number);const start=approvedStart??localToUTC(day,h*60+m).toISOString();const response=await fetch('/api/admin/moxo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,start,duration:approvedStart?duration:60,phone_verified:data.get('verified')==='on'})});const result=await response.json();if(!response.ok)throw Error(result.error==='slot_taken'?'המועד חופף למבדק MOXO אחר.':'לא ניתן להשלים את האישור. רעננו את הרשימה לפני ניסיון נוסף.');setMessage(result.notification==='accepted'?'המועד אושר. ההודעה התקבלה אצל ספק WhatsApp; אין עדיין אישור מסירה.':`המועד אושר. שליחת הודעה: ${result.notification}. יש לבדוק את ספק WhatsApp; אין להניח שהמטופל קיבל הודעה.`);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <form onSubmit={submit} className="space-y-3"><fieldset disabled={busy} className="flex flex-wrap gap-3">{!approvedStart&&<><label>תאריך (שעון ישראל)<select name="day" required value={day} onChange={e=>setDay(e.target.value)} className="block border rounded p-2"><option value="">בחירת יום שלישי / חמישי</option>{dates.map(d=><option key={d} value={d}>{d}</option>)}</select></label><label>שעה<select key={day} name="time" required disabled={!day} className="block border rounded p-2"><option value="">בחירת שעה</option>{day&&moxoHours(day).map(t=><option key={t} value={t}>{t}</option>)}</select></label><p>משך המבדק: 60 דקות</p></>}<label className="flex gap-2 items-center"><input name="verified" type="checkbox" required/>אימתתי את מספר הנייד מול איש הקשר ואת הסכמתו לקבלת ההודעה</label><button className="btn-primary" type="submit">{busy?'מעבד…':approvedStart?'בדיקת שליחת האישור':'אישור מועד ושליחת WhatsApp'}</button></fieldset>{message&&<p role="status" className="text-sm bg-slate-100 p-3 rounded">{message}</p>}</form>;
}
