'use client';
import { useRef, useState, type FormEvent } from 'react';
import { localParts } from '@/lib/booking/schedule';
const copy={
 he:{inactive:'הזמנה מקוונת של MOXO עדיין אינה פעילה. לתיאום מול הצוות פנו למכון ב־WhatsApp.',title:'בקשת תור למבדק MOXO',intro:'מלאו פרטי קשר ויום מועדף. המכון יבדוק את הבקשה ויאשר מועד; רק לאחר אישור המכון תישלח הודעת WhatsApp עם פרטי התור.',patient:'שם המטופל/ת',contact:'שם איש הקשר / הורה',phone:'מספר נייד ל־WhatsApp',date:'יום מועדף (לא חובה)',consent:'אני מאשר/ת למכון ליצור איתי קשר ולשלוח אישור תור ב־WhatsApp למספר שמסרתי.',submit:'שליחת בקשה לאישור המכון',success:'הבקשה נשמרה וממתינה לאישור המכון. עדיין לא נקבע תור.',error:'לא ניתן לאשר שהבקשה נקלטה כרגע. אפשר לנסות שוב או לפנות למכון ב־WhatsApp.',contactUs:'פנייה למכון ב־WhatsApp',privacy:'יש למלא פרטי קשר בלבד, ללא מסמכים או מידע רפואי.',sending:'שומר בקשה…'},
 ar:{inactive:'طلب مواعيد MOXO عبر الموقع غير متاح بعد. للتنسيق مع الطاقم تواصلوا مع المعهد عبر واتساب.',title:'طلب موعد لفحص MOXO',intro:'أدخلوا بيانات التواصل واليوم المفضّل. يراجع المعهد الطلب ويوافق على الموعد؛ تُرسل رسالة واتساب بتفاصيل الموعد فقط بعد موافقة المعهد.',patient:'اسم المريض/ة',contact:'اسم جهة الاتصال / ولي الأمر',phone:'رقم الجوال للواتساب',date:'اليوم المفضّل (اختياري)',consent:'أوافق على تواصل المعهد معي وإرسال تأكيد الموعد عبر واتساب إلى الرقم الذي أدخلته.',submit:'إرسال الطلب لموافقة المعهد',success:'تم حفظ الطلب وهو بانتظار موافقة المعهد. لم يُحجز موعد بعد.',error:'تعذّر تأكيد استلام الطلب حاليًا. يمكن المحاولة مجددًا أو التواصل مع المعهد عبر واتساب.',contactUs:'التواصل مع المعهد عبر واتساب',privacy:'يرجى إدخال بيانات التواصل فقط، دون مستندات أو معلومات طبية.',sending:'جارٍ حفظ الطلب…'},
 en:{inactive:'Online MOXO requests are not active yet. Contact institute staff on WhatsApp to arrange an appointment.',title:'Request a MOXO appointment',intro:'Enter your contact details and preferred day. The institute reviews and approves the appointment; a WhatsApp confirmation is sent only after institute approval.',patient:'Patient name',contact:'Contact / parent name',phone:'Mobile number for WhatsApp',date:'Preferred day (optional)',consent:'I agree to be contacted by the institute and receive an appointment confirmation on WhatsApp at the number I entered.',submit:'Submit for institute approval',success:'Your request was saved and awaits institute approval. No appointment has been booked yet.',error:'We could not confirm receipt of your request. Try again or contact the institute on WhatsApp.',contactUs:'Contact the institute on WhatsApp',privacy:'Contact details only. Do not include medical documents or medical information.',sending:'Saving request…'}
};
export default function RequestForm({language,enabled}:{language:'he'|'ar'|'en';enabled:boolean}){
 const t=copy[language],request=useRef<Record<string,unknown>|null>(null);
 const [busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(false),[uncertain,setUncertain]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);
 if(!request.current){let phone=String(fields.get('phone')).replace(/[\s().-]/g,'');if(phone.startsWith('0'))phone='+972'+phone.slice(1);if(phone.startsWith('972'))phone='+'+phone;
 request.current={id:crypto.randomUUID(),patient_name:fields.get('patient_name'),contact_name:fields.get('contact_name'),phone,language,consent:fields.get('consent')==='on',website:'',...(fields.get('preferred_date')?{preferred_date:fields.get('preferred_date')}:{})};}
 setBusy(true);setError(false);
 try{const response=await fetch('/api/moxo/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request.current)});const result=await response.json();if(!response.ok||result.received!==true){if(response.status<500){request.current=null;setUncertain(false);}else setUncertain(true);throw Error();}setDone(true);}catch{setError(true);setUncertain(!!request.current);}finally{setBusy(false);}}
 return <div className="card max-w-2xl mx-auto" dir={language==='en'?'ltr':'rtl'}><h1 className="text-3xl font-bold text-teal-800">{t.title}</h1><p className="my-4">{t.intro}</p>{!enabled?<p role="status" className="p-4 bg-amber-50 rounded-lg">{t.inactive}</p>:done?<p role="status" className="p-4 bg-teal-50 rounded-lg">{t.success}</p>:<form onSubmit={submit} className="space-y-4"><fieldset disabled={busy||uncertain} className="space-y-4">{(['patient_name','contact_name','phone'] as const).map((name,i)=><label key={name} className="block">{[t.patient,t.contact,t.phone][i]}<input className="input w-full border p-3 rounded-lg mt-1" name={name} required minLength={i===2?9:2} maxLength={i===2?20:100} type={i===2?'tel':'text'} autoComplete={i===2?'tel':'name'} dir={i===2?'ltr':undefined}/></label>)}<label className="block">{t.date}<input name="preferred_date" type="date" min={localParts(new Date()).date} className="block border p-3 rounded-lg"/></label><label className="flex gap-3"><input name="consent" type="checkbox" required/><span>{t.consent}</span></label><p className="text-sm text-slate-500">{t.privacy}</p></fieldset>{error&&<p role="alert" className="text-red-700">{t.error}</p>}<button disabled={busy} className="btn-primary" type="submit">{busy?t.sending:t.submit}</button></form>}<a className="block mt-5 text-teal-800 underline" href="https://wa.me/972544020043">{t.contactUs}</a></div>;
}
