import {z} from 'zod';
export const regions=['europe','americas','asia','africa','oceania','other'] as const;
export const requestSchema=z.object({id:z.string().uuid(),parent:z.string().trim().min(2).max(100),email:z.string().trim().email().max(254),phone:z.string().trim().regex(/^\+?[0-9 ()-]{8,22}$/),country:z.string().trim().min(2).max(80),city:z.string().trim().min(2).max(100),region:z.enum(regions),start:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),end:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),children:z.number().int().min(1).max(10),consent:z.literal(true),website:z.literal('')}).strict();
const money=z.number().int().min(0).max(10000000);
const legacyPricingSchema=z.object({enabled:z.boolean(),base:money,daily:money,extra_child_daily:money,region_daily:z.object({europe:money,americas:money,asia:money,africa:money,oceania:money,other:money}).strict(),scope:z.string().trim().min(10).max(3000),response_time:z.string().trim().min(3).max(300)}).strict();
export const familyPricingSchema=z.object({enabled:z.boolean(),model:z.literal('family_week_usd'),currency:z.literal('USD'),weekly:money,scope:z.string().trim().min(10).max(3000),response_time:z.string().trim().min(3).max(300)}).strict();
export const pricingSchema=z.union([familyPricingSchema,legacyPricingSchema]);
export const familyPricing={enabled:true,model:'family_week_usd' as const,currency:'USD' as const,weekly:5000,scope:'ייעוץ רפואי מרחוק בזמן השהייה בחו״ל לכל המשפחה: בירור תלונות ושאלות רפואיות, הדרכה להורים, ייעוץ לגבי טיפול קיים ומעקב אחר ההמלצות. לפי הצורך — שיחה מתואמת והכוונה לבדיקה או לטיפול רפואי מקומי. תחום המומחיות הוא רפואת ילדים; שאלות של בני משפחה מבוגרים ייענו בהתאם לתחום הסמכות וההתאמה הרפואית. המחיר אינו כולל בדיקות, תרופות, טיפול מקומי או פינוי. אין הבטחה להנפקת מרשם התקף במדינת היעד.',response_time:'זמינות לייעוץ רפואי 24/7 לאורך שבוע השירות. אין התחייבות למענה מיידי; במצב חירום יש לפנות מיד לשירותי החירום המקומיים.'};
export function quoteCurrency(p:unknown){return (p as {currency?:string}|null)?.currency==='USD'?'USD':'ILS';}
export function stayDays(start:string,end:string){const a=Date.parse(start+'T00:00:00Z'),b=Date.parse(end+'T00:00:00Z');if(!Number.isFinite(a)||!Number.isFinite(b)||new Date(a).toISOString().slice(0,10)!==start||new Date(b).toISOString().slice(0,10)!==end)return null;const days=(b-a)/86400000+1;return Number.isInteger(days)&&days>=1&&days<=365?days:null;}
export function quote(p:unknown,b:{start:string;end:string;children:number;region:typeof regions[number]}){const days=stayDays(b.start,b.end);if(!days)throw Error('invalid_dates');const parsed=pricingSchema.safeParse(p);if(!parsed.success||!parsed.data.enabled)return {days,total:null,pricing:null};const c=parsed.data;if('model' in c)return {days,total:days<=7?c.weekly:null,pricing:c};return {days,total:c.base+days*(c.daily+c.region_daily[b.region]+Math.max(0,b.children-1)*c.extra_child_daily),pricing:c};}
