'use client';
import {useEffect,useState} from 'react';
import {domains,RATINGS,labels,SOURCE,Role} from '@/lib/development/schema';
export default function Form(){
 const [token,setToken]=useState(''),[info,setInfo]=useState<any>(null),[answers,setAnswers]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[teacher,setTeacher]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{const t=location.hash.slice(1);if(!/^[a-f0-9]{64}$/.test(t)){setError('למילוי השאלון יש לבקש מהמכון קישור אישי.');return;}setToken(t);fetch('/api/development',{headers:{Authorization:'Bearer '+t},cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setInfo(d);setAnswers(d.answers);}).catch(e=>setError(e.message));},[]);
 async function save(submit:boolean){setBusy(true);setError('');setSaved(false);try{const r=await fetch('/api/development',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({answers,submit})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSaved(true);if(submit)setInfo({...info,submitted:true});if(d.education_token)setTeacher(location.origin+'/development#'+d.education_token);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function field(k:string,value:string){setAnswers(a=>({...a,[k]:value}));setSaved(false);}
 const role=info?.role as Role;
 return <>{error&&<p role="alert" className="bg-red-50 text-red-800 p-3 my-3">{error}</p>}{info&&<><h2 className="text-xl my-3">{info.child_name} · {role==='parent'?'שאלון הורים':role==='teacher'?'שאלון מורה':'שאלון גננת'}</h2><p className="text-sm mb-4">טופס איסוף מידע של המכון, בהשראת תחומי ההערכה של מכבי. אינו תחליף לשאלון הרשמי ואינו אבחון. <a className="underline" href={SOURCE} target="_blank" rel="noreferrer">לערכה הרשמית</a></p>{info.submitted?<div className="bg-teal-50 p-4"><h3 className="font-bold">השאלון נשלח למכון</h3>{teacher?<><p>העבירו את הקישור האישי למורה או לגננת בלבד. שמרו אותו כעת; ניתן לקבל קישור חדש מהמכון.</p><input readOnly value={teacher} dir="ltr" className="w-full border p-2 my-3"/><button onClick={()=>navigator.clipboard.writeText(teacher).catch(()=>setError('ניתן להעתיק את הקישור מהשדה'))} className="border rounded p-3">העתקת קישור</button><a className="inline-block p-3 text-teal-800 underline" href={'https://wa.me/?text='+encodeURIComponent('שלום, נשמח למילוי שאלון המסגרת החינוכית בקישור האישי: '+teacher)} target="_blank" rel="noreferrer">שיתוף בוואטסאפ</a></>:<p>הצוות יבדוק את המידע לאחר קבלת שני השאלונים. אם חסר קישור למסגרת, פנו למכון.</p>}</div>:<form onSubmit={e=>{e.preventDefault();save(true);}}><p className="mb-4">יש לבחור תשובה בכל תחום. שמירת טיוטה מאפשרת לחזור דרך אותו קישור בתוך 30 יום. אין להעביר את הקישור לאדם אחר.</p>{Object.entries(labels).filter(([k])=>role==='parent'?!['setting','support'].includes(k):!['reason','history','family'].includes(k)).map(([k,label])=><label key={k} className="block my-4">{label}{k!=='notes'?' *':''}<textarea required={k!=='notes'} maxLength={3000} value={answers[k]||''} onChange={e=>field(k,e.target.value)} className="block border rounded-lg w-full p-3 mt-1"/></label>)}{domains[role].map((label,i)=><fieldset key={i} className="border rounded-xl p-4 my-4"><legend className="font-semibold px-2">{label} *</legend><select required value={answers['d'+i]||''} onChange={e=>field('d'+i,e.target.value)} className="w-full border p-3 rounded-lg"><option value="">בחרו תשובה</option>{RATINGS.map(r=><option key={r}>{r}</option>)}</select><label className="block text-sm mt-3">דוגמה או הסבר (רשות)<textarea maxLength={3000} value={answers['n'+i]||''} onChange={e=>field('n'+i,e.target.value)} className="w-full border p-2 rounded-lg"/></label></fieldset>)}<p className="text-sm">בשליחה אני מאשר/ת שהתשובות משקפות את דיווחי ויועברו לצוות המכון במסגרת הפנייה. לאחר שליחה התשובות ננעלות.</p><div className="flex gap-3 my-6"><button disabled={busy} type="button" onClick={()=>save(false)} className="border rounded-lg p-3">שמירת טיוטה</button><button disabled={busy} className="bg-teal-700 text-white p-3 rounded-lg">{busy?'שומר…':'שליחה למכון'}</button></div>{saved&&<p role="status">המידע נשמר בהצלחה</p>}</form>}</>}</>;
}
