'use client';
import {useEffect,useState} from 'react';
const states:Record<string,string>={parent:'ממתין להורה',education:'ממתין למסגרת',review:'לבדיקת רופא',uploading:'העלאת מסמך',approved:'מאושר לשליחה',sending:'בשליחה',accepted:'התקבל אצל ספק הדואר — מסירה לא אומתה',unknown:'מצב שליחה לא ידוע — נדרשת בדיקה',delivered:'נמסר',bounced:'נדחה'};
const kinds:Record<string,string>={parent_original:'שאלון מכבי מלא — הורה',education_original:'שאלון מכבי מלא — מסגרת',referral:'הפניה רפואית',consent:'הסכמה חתומה'};
export default function Workspace({editable}:{editable:boolean}){
 const [cases,setCases]=useState<any[]>([]),[record,setRecord]=useState<any>(null),[documents,setDocuments]=useState<any[]>([]),[ready,setReady]=useState(false),[destination,setDestination]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[link,setLink]=useState(''),[summary,setSummary]=useState(''),[confirmed,setConfirmed]=useState(false);
 async function api(body?:any,id?:string){const r=await fetch('/api/admin/development'+(id?'?id='+encodeURIComponent(id):''),body?{method:'POST',...(body instanceof FormData?{body}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}:{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'הפעולה נכשלה');return d;}
 async function refresh(id?:string){const d=await api(undefined,id);setReady(d.mail_configured);setDestination(d.destination);if(id){setRecord(d.case);setDocuments(d.documents);setSummary(d.case.summary||'');setConfirmed(false);}else setCases(d.cases);}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message));},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'שגיאה');}finally{setBusy(false);}}
 async function action(action:string,extra:any={}){await run(async()=>{const d=await api({action,id:record.id,...extra});if(d.token)setLink(location.origin+'/development#'+d.token);await refresh(record.id);await refresh();setMessage(action==='send'?'הבקשה התקבלה אצל ספק הדואר. אין עדיין אישור מסירה.':'הפעולה נשמרה');});}
 const input='w-full border rounded-lg p-3';const btn='rounded-lg bg-teal-800 text-white px-4 py-2 disabled:opacity-40';
 return <div className="space-y-6" dir="rtl"><h1 className="text-2xl font-bold">הפניות להתפתחות הילד</h1><p className="rounded-xl bg-amber-50 border p-4">שאלוני הקליטה כאן משלימים את טפסי מכבי ואינם מחליפים אותם. שליחה מחייבת מסמכי מקור מלאים, הסכמה ובדיקת רופא. המסלול הנוכחי: מגיל שנה עד לפני גיל שבע.</p><p>יעד: <span dir="ltr">{destination}</span> · חיבור דואר: {ready?'הוגדר — נדרשת בדיקת מסירה':'טרם הוגדר'}</p>{message&&<p role="status" className="p-3 border rounded bg-white">{message}</p>}{link&&<div className="p-4 bg-teal-50 rounded"><p>קישור אישי — למסירה רק לנמען המתאים. יצירת קישור חדש מבטלת את הקודם.</p><input className={input} dir="ltr" readOnly value={link}/><button className={btn} onClick={()=>run(async()=>{await navigator.clipboard.writeText(link);setMessage('הקישור הועתק');})}>העתקה</button></div>}
 {editable&&<details className="bg-white p-4 rounded-xl border"><summary className="cursor-pointer font-bold">פתיחת פנייה חדשה</summary><form className="grid gap-3 mt-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const d=await api({action:'create',data:{child_name:f.get('child_name'),birth_date:f.get('birth_date'),parent_name:f.get('parent_name'),phone:f.get('phone'),education_role:f.get('education_role'),consent:f.get('consent')==='on'}});setLink(location.origin+'/development#'+d.parent_token);await refresh();await refresh(d.id);});}}>{[['child_name','שם הילד/ה','text'],['birth_date','תאריך לידה','date'],['parent_name','שם ההורה','text'],['phone','טלפון ההורה','tel']].map(([name,label,type])=><label key={name}>{label}<input required name={name} type={type} className={input}/></label>)}<label>מסגרת<select name="education_role" className={input}><option value="kindergarten">גן</option><option value="teacher">בית ספר</option></select></label><label><input name="consent" type="checkbox" required/> התקבלה הסכמת ההורה לפתיחת הפנייה ולשליחת הקישור האישי</label><button disabled={busy} className={btn}>פתיחה ויצירת קישור להורה</button></form></details>}
 <div className="grid gap-4 lg:grid-cols-3"><section className="space-y-2"><h2 className="font-bold">100 הפניות האחרונות</h2>{cases.map(c=><button key={c.id} disabled={busy} onClick={()=>{setLink('');run(()=>refresh(c.id));}} className="w-full text-right border p-4 bg-white rounded-lg"><strong>{c.child_name}</strong><p>{states[c.status]||c.status}</p><small>הורה: {c.parent_submitted_at?'הושלם':'ממתין'} · מסגרת: {c.education_submitted_at?'הושלם':'ממתין'}</small></button>)}</section>{record&&<section className="lg:col-span-2 bg-white border p-5 rounded-xl space-y-4"><h2 className="text-xl font-bold">{record.child_name}</h2><p>{states[record.status]||record.status}</p>{editable&&['parent','education','review'].includes(record.status)&&<div className="flex flex-wrap gap-2"><button className={btn} disabled={busy||!!record.parent_submitted_at} onClick={()=>action('link',{role:'parent'})}>קישור חדש להורה</button><button className={btn} disabled={busy||!record.parent_submitted_at||!!record.education_submitted_at} onClick={()=>action('link',{role:'education'})}>קישור חדש למסגרת</button></div>}
 <h3 className="font-bold">מסמכים מצורפים</h3>{Object.entries(kinds).map(([kind,label])=>{const doc=documents.find(d=>d.kind===kind);return <div className="border rounded p-3" key={kind}><p>{label}: {doc?<a className="text-teal-800 underline" href={'/api/admin/development?id='+record.id+'&document='+doc.id}>הורדת המסמך לבדיקה</a>:'חסר'}</p>{editable&&['parent','education','review'].includes(record.status)&&<label>העלאת PDF עד 5MB<input className="block max-w-full" type="file" accept="application/pdf" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(!file)return;const f=new FormData();f.set('id',record.id);f.set('kind',kind);f.set('file',file);run(async()=>{await api(f);await refresh(record.id);setMessage('המסמך נשמר');});}}/></label>}</div>;})}
 <h3 className="font-bold">ריכוז הדיווחים לבדיקת רופא</h3><textarea className={input} rows={20} value={summary} readOnly={!editable||record.status!=='review'} onChange={e=>setSummary(e.target.value)}/>{editable&&record.status==='review'&&<><label className="block"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> בדקתי את הדיווחים, הסיכום, מסמכי המקור וההסכמה להעברה ליעד המוצג</label><button className={btn} disabled={busy||!confirmed} onClick={()=>action('approve',{summary,confirmed})}>שמירת סיכום ואישור רפואי</button></>}{editable&&record.status==='approved'&&<button className={btn} disabled={busy||!ready} onClick={()=>action('send')}>שליחת הסיכום והמסמכים להתפתחות הילד</button>}<p className="text-sm">אישור ספק דואר אינו מעיד שהפנייה נקלטה במערכת מכבי.</p></section>}</div></div>;
}
