'use client';
import {useRef,useState,type FormEvent} from 'react';
import {classes,classLabels} from '@/lib/classes/catalog';
const copy={
 he:['חוגי המכון — רשימת מתעניינים','הרשימות פתוחות לפי סוג החוג. עדיין אין מועד פתיחה או מקום מאושר. כשקבוצה תיפתח ניצור קשר עם ההורים להשלמת הרשמה; התשלום יוסדר בהמשך.','שם הילד/ה','שם ההורה','נייד ישראלי','בחירת חוג','אני הורה/אפוטרופוס ומסכים/ה לשמירת הפרטים ולקבלת עדכון על פתיחת החוג.','הצטרפות לרשימת המתעניינים','הפרטים נשמרו ברשימת החוג. ניצור קשר כשהקבוצה תיפתח.','לא התקבל אישור שמירה. בדקו את הפרטים ונסו שוב.'],
 ar:['دورات المعهد — قائمة المهتمين','القوائم مفتوحة حسب الدورة. لا يوجد موعد بدء أو مقعد مؤكد بعد. عند افتتاح المجموعة نتواصل مع الأهل لإتمام التسجيل؛ الدفع لاحقًا.','اسم الطفل/ة','اسم ولي الأمر','رقم محمول إسرائيلي','اختيار الدورة','أنا ولي الأمر وأوافق على حفظ البيانات والتواصل معي عند افتتاح الدورة.','الانضمام لقائمة المهتمين','حُفظت البيانات في قائمة الدورة. سنتواصل عند افتتاح المجموعة.','لم يتم تأكيد الحفظ. تحققوا من البيانات وحاولوا مجددًا.'],
 en:['Institute classes — interest lists','Join an open interest list by class. No start date or place is confirmed yet. We will contact parents when a group opens to complete registration; payment comes later.','Child’s name','Parent’s name','Israeli mobile','Choose a class','I am the parent/guardian and agree to storage and updates when this class opens.','Join interest list','Saved to the class interest list. We will contact you when the group opens.','No save confirmation. Check your details and retry.']};
export default function InterestForm({language,initial}:{language:'he'|'ar'|'en';initial:string}){
 const t=copy[language],id=useRef(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(false);
 const [duplicate,setDuplicate]=useState(false);
 const emailCopy={
 he:['כתובת המייל של ההורה','העדכונים ותיאום ההרשמה ייעשו במייל בלבד. הפרטים אינם משמשים להרשמה לדיוור פרסומי.','כבר קיימת פנייה לחוג עם הפרטים האלה. לא שינינו את כתובת הקשר. להשלמה או לתיקון כתובת המייל פנו למזכירות ב־magickids@magickidsinstitute.com.'],
 ar:['البريد الإلكتروني لولي الأمر','التحديثات وتنسيق التسجيل عبر البريد الإلكتروني فقط. لن تُستخدم البيانات للاشتراك في رسائل إعلانية.','يوجد طلب سابق لهذه الدورة بهذه البيانات. لم نغيّر بيانات التواصل. لإضافة البريد أو تصحيحه تواصلوا مع السكرتارية: magickids@magickidsinstitute.com.'],
 en:['Parent email address','Updates and registration coordination are by email only. These details do not subscribe you to marketing emails.','An interest request already exists with these details. We did not change the contact address. To add or correct it, email magickids@magickidsinstitute.com.']
 }[language];
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!id.current)id.current=crypto.randomUUID();const f=new FormData(e.currentTarget);setBusy(true);setError(false);
 setDuplicate(false);
 try{const r=await fetch('/api/classes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id.current,patient:f.get('patient'),contact:f.get('contact'),phone:f.get('phone'),email:f.get('email'),classType:f.get('classType'),language,consent:f.get('consent')==='on',website:f.get('website')})});const b=await r.json();if(b.error==='already_registered'){setDuplicate(true);return;}if(!r.ok||!b.received)throw Error();setDone(true);}catch{setError(true);}finally{setBusy(false);}}
 return <main dir={language==='en'?'ltr':'rtl'} className="max-w-xl mx-auto p-6 space-y-5"><nav className="flex gap-4"><a href="?lang=he">עברית</a><a href="?lang=ar">العربية</a><a href="?lang=en">English</a></nav><h1 className="text-3xl font-bold text-teal-800">{t[0]}</h1><p>{t[1]}</p>{done?<p role="status" className="card">{t[8]}</p>:<form onSubmit={submit} className="card space-y-4"><fieldset disabled={busy} className="space-y-4">{['patient','contact','phone'].map((name,i)=><label key={name} className="block">{t[i+2]}<input className="block border rounded p-2 w-full" name={name} type={name==='phone'?'tel':'text'} minLength={2} maxLength={100} required autoComplete={name==='phone'?'tel':'off'}/></label>)}<label className="block">{emailCopy[0]}<input className="block border rounded p-2 w-full" name="email" type="email" autoComplete="email" dir="ltr" maxLength={254} required aria-describedby="email-help"/></label><p id="email-help" className="text-sm">{emailCopy[1]}</p><label className="block">{t[5]}<select name="classType" required defaultValue={classes.includes(initial as typeof classes[number])?initial:''} className="block border rounded p-2 w-full"><option value="">—</option>{classes.map((c,i)=><option key={c} value={c}>{classLabels[language][i]}</option>)}</select></label><input name="website" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true"/><label className="block"><input type="checkbox" name="consent" required/> {t[6]}</label><button className="btn-primary">{busy?'…':t[7]}</button></fieldset>{error&&<p role="alert">{t[9]}</p>}{duplicate&&<p role="status">{emailCopy[2]}</p>}</form>}</main>;
}
