import {requireStaff} from '@/lib/admin/auth';
import {getSupabaseAdmin} from '@/lib/supabase';
import {labels,treatments} from '@/lib/treatments/schema';
import StaffActions from '@/components/treatments/StaffActions';
export const dynamic='force-dynamic';
const stateNames:Record<string,string>={pending:'ממתין לתיאום',contacted:'נוצר קשר',scheduled:'נקבע תור',closed:'סגור'};
export default async function Page({searchParams}:{searchParams:{treatment?:string;status?:string}}){
 await requireStaff();let query=getSupabaseAdmin().from('treatment_requests').select('id,patient_name,contact_name,phone,treatment,language,availability,status,therapist,scheduled_at,duration_minutes,created_at').order('created_at',{ascending:true}).limit(200);
 if(treatments.includes(searchParams.treatment as typeof treatments[number]))query=query.eq('treatment',searchParams.treatment!);
 if(searchParams.status&&searchParams.status in stateNames)query=query.eq('status',searchParams.status);else query=query.neq('status','closed');
 const result=await query;
 const date=(s:string)=>new Intl.DateTimeFormat('he-IL',{timeZone:'Asia/Jerusalem',dateStyle:'medium',timeStyle:'short'}).format(new Date(s));
 return <section className="space-y-5"><h1 className="text-3xl font-bold text-teal-800">פניות וטיפולים במכון</h1><p>הפניות מוצגות מהוותיקה לחדשה, לפי סוג הטיפול שנבחר. לפני שיבוץ יש לתאם עם ההורה ולבדוק זמינות מטפל/ת וחדר. התורים נשמרים כאן במערכת המכון; אינם מועתקים אוטומטית ליומני Google של המרפאות.</p><form className="flex flex-wrap gap-3"><label>טיפול<select name="treatment" defaultValue={searchParams.treatment??''} className="input"><option value="">כל הטיפולים</option>{treatments.map((v,i)=><option key={v} value={v}>{labels.he[i]}</option>)}</select></label><label>מצב<select name="status" defaultValue={searchParams.status??''} className="input"><option value="">כל הפניות הפתוחות</option>{Object.entries(stateNames).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><button className="btn-secondary">סינון</button></form>{result.error?<p role="alert">לא ניתן לטעון את הפניות. יש לבדוק את חיבור המערכת.</p>:!result.data?.length?<p className="card">אין פניות להצגה.</p>:result.data.map((row,i)=><article key={row.id} className="card space-y-3"><h2 className="text-xl font-bold">{i+1}. {row.patient_name} · {labels.he[treatments.indexOf(row.treatment)]??row.treatment}</h2><p>{stateNames[row.status]} · התקבלה: {date(row.created_at)} · שפה: {row.language}</p><p>{row.contact_name} · <a dir="ltr" href={`tel:${row.phone}`}>{row.phone}</a> · <a href={`https://wa.me/${row.phone.replace('+','')}`} target="_blank" rel="noopener noreferrer">WhatsApp</a></p>{row.availability&&<p>זמינות המשפחה: {row.availability}</p>}{row.status==='scheduled'&&<p className="font-bold text-teal-800">{date(row.scheduled_at)} · {row.duration_minutes} דקות · {row.therapist}</p>}<StaffActions id={row.id} status={row.status}/></article>)}{result.data?.length===200&&<p>מוצגות 200 הפניות הראשונות. סננו לפי סוג טיפול ומצב להמשך טיפול.</p>}</section>;
}
