'use client';
import {useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {type Candidate,statuses} from '@/lib/recruitment/schema';
import {treatments,labels} from '@/lib/treatments/schema';
const blank={name:'',email:'',phone:'',treatments:[] as string[],experience:'',notes:'',status:'new'};
export default function Manager({candidates}:{candidates:Candidate[]}){
 const router=useRouter(),[editing,setEditing]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function send(body:unknown){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/recruitment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error==='email_exists'?'כבר קיים מטפל עם המייל הזה. בדקו בניהול מטפלים; לא נוצר כרטיס כפול.':'הפעולה לא נשמרה. בדקו את הפרטים ונסו שוב.');setEditing(null);setMessage(d.converted?'נוצר כרטיס מטפל לא פעיל. עברו לניהול מטפלים, הגדירו שעות והפעילו קבלת פניות.':d.deleted?'המועמדות נמחקה. כרטיס מטפל קיים לא נמחק.':'השינויים נשמרו.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'אירעה שגיאה');}finally{setBusy(false);}}
 function save(e:FormEvent){e.preventDefault();void send({action:'save',profile:editing});}
 return <div className="space-y-4"><button disabled={busy} className="btn-primary" onClick={()=>setEditing({...blank})}>הוספת מועמד/ת ידנית</button><p role="status">{message}</p>{editing&&<form onSubmit={save} className="card space-y-3"><fieldset disabled={busy} className="space-y-3"><h2 className="text-xl font-bold">פרטי מועמדות</h2>{[['name','שם מלא','text'],['email','מייל','email'],['phone','טלפון','tel']].map(([key,label,type])=><label className="block" key={key}>{label}<input type={type} required className="input" value={editing[key]} maxLength={key==='name'?100:key==='phone'?25:254} onChange={e=>setEditing({...editing,[key]:e.target.value})}/></label>)}<div className="flex flex-wrap gap-3">{treatments.map((t,i)=><label key={t}><input type="checkbox" checked={editing.treatments.includes(t)} onChange={e=>setEditing({...editing,treatments:e.target.checked?[...editing.treatments,t]:editing.treatments.filter((v:string)=>v!==t)})}/> {labels.he[i]}</label>)}</div><label className="block">הכשרה וניסיון<textarea className="input" maxLength={3000} rows={4} value={editing.experience} onChange={e=>setEditing({...editing,experience:e.target.value})}/></label><label className="block">הערות פנימיות לצוות<textarea className="input" maxLength={5000} rows={3} value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label><label className="block">מצב<select className="input" value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button disabled={!editing.treatments.length} className="btn-primary">שמירה</button><button type="button" className="btn-ghost" onClick={()=>setEditing(null)}>ביטול</button></fieldset></form>}
 {!candidates.length&&<p className="card">אין מועמדים להצגה. אפשר להוסיף ידנית או לשלוח את טופס המועמדות.</p>}
 {candidates.map(c=><article key={c.id} className="card space-y-3"><h2 className="text-xl font-bold">{c.name} · {statuses[c.status]}</h2><p><a href={`mailto:${c.email}`}>{c.email}</a> · <a href={`tel:${c.phone}`}>{c.phone}</a></p><p>{c.treatments.map(t=>labels.he[treatments.indexOf(t as any)]).join(' · ')}</p><p className="whitespace-pre-wrap">{c.experience}</p>{c.notes&&<p className="whitespace-pre-wrap bg-amber-50 p-3">הערות צוות: {c.notes}</p>}<div className="flex flex-wrap gap-3"><button disabled={busy} className="btn-secondary" onClick={()=>setEditing({id:c.id,name:c.name,email:c.email,phone:c.phone,treatments:c.treatments,experience:c.experience,notes:c.notes,status:c.status})}>עריכה ומצב גיוס</button>{c.therapist_id?<Link href="/admin/therapists" className="underline">כרטיס מטפל נוצר — לניהול מטפלים</Link>:<button disabled={busy} className="btn-primary" onClick={()=>{if(confirm(`לקבל את ${c.name} וליצור כרטיס מטפל לא פעיל? יש להגדיר תחומים ושעות לפני הפעלה.`))void send({action:'accept',id:c.id});}}>קבלה ויצירת כרטיס מטפל</button>}<button disabled={busy} className="text-red-700 underline" onClick={()=>{if(confirm(`למחוק לצמיתות את המועמדות של ${c.name}, כולל הפרטים וההערות? כרטיס מטפל וטיפולים קיימים יישמרו.`))void send({action:'delete',id:c.id,confirmed:true});}}>מחיקת מועמדות</button></div></article>)}
 </div>;
}
