import { requireStaff } from '@/lib/admin/auth';
import { getSupabaseAdmin } from '@/lib/supabase';
import ApproveRequest from '@/components/moxo/ApproveRequest';
import CalendarSync from '@/components/moxo/CalendarSync';
export const dynamic='force-dynamic';
export default async function Page(){await requireStaff();const db=getSupabaseAdmin();const result=await db.from('moxo_requests').select('*').in('status',['pending','approved']).order('created_at',{ascending:false}).limit(200);
 const notices=await db.from('clinic_notifications').select('id,state').like('id','moxo:%').limit(1000);
 return <div className="space-y-5"><h1 className="text-3xl font-bold text-teal-800">בקשות ויומן מבדקי MOXO</h1><p>מבדקים בימי שלישי וחמישי 09:00–13:00, שעה לכל מבדק. בקשה אינה תור מאושר. לאחר אימות פרטי הקשר ובחירת מועד, האישור נשמר במערכת ונשלח ב־WhatsApp. לאחר האישור המבדק מסונכרן גם ליומן Google של המכון; מצב הסנכרון מוצג בכל בקשה.</p><a href="/admin/intake" className="underline">קליטה וזימון לאבחון עם שרה ↗</a>{result.error?<p role="alert" className="card text-red-700">לא ניתן לטעון את הבקשות. יש לבדוק שחיבור מסד הנתונים ועדכון טבלאות MOXO הושלמו.</p>:!result.data?.length?<p className="card">אין בקשות להצגה.</p>:result.data.map(row=><article key={row.id} className="card space-y-4"><h2 className="text-xl font-bold">{row.patient_name}</h2><p>{row.contact_name} · <span dir="ltr">{row.phone}</span></p><p>{row.status==='approved'?'מאושר':'ממתין לאישור'} · יום מועדף: {row.preferred_start?new Intl.DateTimeFormat('he-IL',{timeZone:'Asia/Jerusalem',dateStyle:'short',timeStyle:'short'}).format(new Date(row.preferred_start)):row.preferred_date??'לא צוין'}</p>{row.scheduled_at&&<p>מועד: {new Intl.DateTimeFormat('he-IL',{timeZone:'Asia/Jerusalem',dateStyle:'full',timeStyle:'short'}).format(new Date(row.scheduled_at))} · {row.duration_minutes} דקות</p>}<p className="text-sm">WhatsApp: {notices.error?'לא ניתן לבדוק':notices.data?.find(n=>n.id===`moxo:${row.id}`)?.state??'טרם נשלח'}</p>{row.status==='approved'&&<CalendarSync id={row.id} status={row.calendar_status??'pending'}/>}<ApproveRequest id={row.id} approvedStart={row.scheduled_at??undefined} duration={row.duration_minutes}/></article>)}</div>;
}
