'use client';
import {useState,FormEvent} from 'react';
import {useRouter} from 'next/navigation';
export default function BookSlot({start,label}:{start:string;label:string}){
  const router=useRouter();const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[requestId,setRequestId]=useState(''),[done,setDone]=useState(false),[locked,setLocked]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setLocked(true);setMessage('');const f=new FormData(e.currentTarget);
    try{const r=await fetch('/api/admin/pediatrics-calendar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId,start,childName:f.get('childName'),parentName:f.get('parentName'),phone:f.get('phone'),consent:true,reminderConsent:false,language:'he',website:''})});const d=await r.json();if(!r.ok||!d.confirmed){const errors:Record<string,string>={slot_taken:'השעה כבר תפוסה. רעננו ובחרו שעה אחרת.',invalid_slot:'המועד חלף או אינו בשעות הפעילות.',rate_limited:'הגעתם למגבלת ההזמנות. נסו שוב מאוחר יותר.',invalid_body:'בדקו את השמות ומספר הטלפון.',processing:'השמירה עדיין בבדיקה. לחצו שוב עם אותם פרטים כדי לבדוק את התוצאה.'};setMessage(errors[d.error]||'לא התקבל אישור שמירה. נסו שוב עם אותם פרטים.');if(['invalid_body','invalid_slot','rate_limited'].includes(d.error))setLocked(false);return;}setDone(true);setMessage('התור נשמר ביומן גוגל.');router.refresh();}catch{setMessage('לא התקבל אישור שמירה. נסו שוב עם אותם פרטים כדי למנוע כפילות.');}finally{setBusy(false);}}
  if(!open)return <button type="button" className="rounded bg-teal-700 text-white px-3 py-2" onClick={()=>{setRequestId(crypto.randomUUID());setOpen(true);}}>קביעת תור</button>;
  return <div className="border rounded p-3 bg-white my-2"><h3 className="font-bold">קביעת תור · {label} · 10 דקות</h3>{!done&&<form onSubmit={submit} className="grid gap-2 mt-2">{[['childName','שם הילד/ה'],['parentName','שם ההורה'],['phone','טלפון']].map(([name,title])=><label key={name}>{title}<input name={name} required readOnly={locked} type={name==='phone'?'tel':'text'} minLength={name==='phone'?7:2} maxLength={name==='phone'?25:100} className="block border rounded p-2 w-full"/></label>)}<p className="text-xs">שמירה ביומן המרפאה. לא נשלחת הודעה להורה בפעולה זו.</p><button disabled={busy} className="bg-teal-700 text-white rounded p-2">{busy?'שומר…':locked?'בדיקת השמירה / ניסיון חוזר':'שמירת התור'}</button>{!locked&&<button type="button" onClick={()=>setOpen(false)}>ביטול</button>}</form>}{message&&<p role="status" className="mt-2">{message}</p>}</div>;
}
