import Link from 'next/link';
import { requireStaff } from '@/lib/admin/auth';
import { loadIntakeQueue } from '@/lib/intake/queue';
import { INTAKE_STAGES } from '@/lib/intake/progress';
import BookAppointment from '../sessions/[id]/BookAppointment';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'קליטה וזימון למרפאת הקשב | ילדי הקסם', robots: { index: false, follow: false } };
export default async function IntakePage({ searchParams }: { searchParams: { stage?: string; q?: string } }) {
  await requireStaff();
  const queue = await loadIntakeQueue().catch(() => null);
  const stage = ['parent','teacher','ready','scheduled','all'].includes(searchParams.stage ?? '') ? searchParams.stage! : 'ready';
  const search = (searchParams.q ?? '').trim().slice(0, 120).toLowerCase();
  const rows = queue?.filter(row => (stage === 'all' || row.stage === stage) && (!search || [row.childName,row.parentName,row.parentPhone].join(' ').toLowerCase().includes(search)));
  return <div className="space-y-6">
    <div className="flex flex-wrap justify-between items-start gap-4"><div><p className="text-sm font-semibold text-[#01696f] mb-2">מרפאת קשב וריכוז</p><h1 className="text-3xl font-bold text-slate-800">קליטה וזימון לפגישה</h1><p className="text-slate-500 mt-2 max-w-2xl">מצב שני השאלונים, פתיחת הדוחות ותיאום פגישה. תיק מוכן לזימון רק לאחר שההורה והמורה שלחו את השאלונים במלואם.</p></div><a href="/onboarding/public" target="_blank" rel="noopener noreferrer" className="btn-primary">פתיחת תיק להורה ↗</a></div>
    {queue === null ? <div className="card text-red-700" role="alert">לא ניתן לטעון כרגע את מצב התיקים. נסו לרענן. אין לראות בכך רשימה ריקה.</div> : <>
      <nav aria-label="סינון לפי שלב הקליטה" className="grid grid-cols-2 xl:grid-cols-5 gap-3">{(['ready','parent','teacher','scheduled','all'] as const).map(value => <Link key={value} href={'/admin/intake?stage='+value} aria-current={stage === value ? 'page' : undefined} className={'rounded-xl p-4 border '+(stage === value ? 'bg-[#01696f] text-white border-[#01696f]' : 'bg-white text-slate-700 border-slate-200 hover:border-teal-600')}><span className="block text-sm">{value === 'all' ? 'כל התיקים הפעילים' : INTAKE_STAGES[value]}</span><strong className="block text-2xl mt-2">{value === 'all' ? queue.length : queue.filter(row => row.stage === value).length}</strong></Link>)}</nav>
      <form className="flex flex-wrap gap-3" method="get"><input type="hidden" name="stage" value={stage}/><label className="flex-1 min-w-48"><span className="sr-only">חיפוש לפי ילד, הורה או טלפון</span><input name="q" defaultValue={search} maxLength={120} placeholder="חיפוש לפי ילד, הורה או טלפון" className="w-full border border-slate-300 rounded-lg p-3 bg-white"/></label><button className="btn-primary" type="submit">חיפוש</button></form>
      <div className="card !p-0 overflow-x-auto"><table className="w-full text-sm text-right"><caption className="text-start p-4 text-slate-500">{rows!.length} תיקים · הרשימה מתעדכנת בכל פתיחה או רענון של העמוד</caption><thead className="bg-slate-100 text-slate-600"><tr>{['ילד/ה והורה','שאלון הורים','שאלון מורה','מצב התהליך','המשך טיפול'].map(title => <th key={title} scope="col" className="p-4 whitespace-nowrap">{title}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows!.map(row => <tr key={row.id} className="align-top"><td className="p-4 min-w-44"><Link className="font-bold text-[#01696f] hover:underline" href={'/admin/sessions/'+row.id}>{row.childName}</Link><p className="text-slate-500 mt-1">{row.parentName}</p>{row.parentPhone && <a href={'tel:'+row.parentPhone.replace(/[^+\d]/g,'')} className="inline-block mt-1 underline" dir="ltr">{row.parentPhone}</a>}</td><td className="p-4"><Completion complete={row.parentComplete} at={row.parentSubmittedAt}/></td><td className="p-4"><Completion complete={row.teacherComplete} at={row.teacherSubmittedAt}/></td><td className="p-4"><span className={'inline-block rounded-full px-3 py-1 text-xs font-bold whitespace-nowrap '+(row.readyToSchedule ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-600')}>{INTAKE_STAGES[row.stage]}</span></td><td className="p-4 space-y-3 min-w-40"><Link className="block text-[#01696f] underline" href={'/admin/sessions/'+row.id}>פתיחת תיק ודוחות</Link>{row.readyToSchedule ? <BookAppointment sessionId={row.id} childName={row.childName} assessmentReady/> : row.hasAppointment ? <Link href={'/admin/sessions/'+row.id+'#appointments'} className="block underline">פרטי הפגישה</Link> : null}</td></tr>)}{rows!.length === 0 && <tr><td colSpan={5} className="text-center text-slate-500 p-10">{search ? 'לא נמצאו תיקים התואמים לחיפוש.' : stage === 'ready' ? 'אין כרגע תיקים שממתינים לזימון לאחר השלמת שני השאלונים.' : 'אין כרגע תיקים בשלב הזה.'}</td></tr>}</tbody></table></div>
      <p className="text-sm text-slate-500">הסימון „מוכן לזימון” מתאר את השלמת השאלונים. האבחון וההחלטה הקלינית נעשים בפגישה עם הרופא.</p>
    </>}
  </div>;
}
function Completion({ complete, at }: { complete: boolean; at: string | null }) { return <div className="min-w-28"><span className={complete ? 'text-emerald-700 font-semibold' : 'text-amber-700'}>{complete ? '✓ הושלם ונשלח' : 'ממתין להשלמה'}</span>{at && <time className="block text-xs text-slate-500 mt-1" dateTime={at}>{new Date(at).toLocaleString('he-IL',{timeZone:'Asia/Jerusalem',dateStyle:'short',timeStyle:'short'})}</time>}</div>; }
