export const bookingCopy = {
  he: {
    cancelLink: 'קישור אישי לביטול התור', keepCancel: 'שמרו את הקישור האישי כדי שתוכלו לבטל גם בהמשך. אין להעביר אותו לאחרים.', reminderConsent: 'אני מאשר/ת קבלת תזכורת בוואטסאפ למספר זה כחצי שעה לפני התור.',
    institute: 'מכון ילדי הקסם', doctor: 'ד״ר בסים נמוז', home: 'לאתר המכון', language: 'שפה',
    clinicPhone: 'טלפון מרפאת הילדים', clinicSecretary: 'מזכירה בשעות פעילות המרפאה',
    pediatrics: 'מרפאת ילדים', adhd: 'מרפאת קשב וריכוז', heading: 'קובעים תור, בקלות.',
    intro: 'בחרו יום ושעה שמתאימים לכם. התור יישמר ביומן המרפאה מיד לאחר השלמת ההזמנה בהצלחה.',
    pedsIntro: 'קביעת תור ישירות בשעה פנויה, ללא אישור המזכירות. לאחר ההזמנה ניתן לבטל דרך הקישור האישי.', adhdIntro: 'קביעת תור לאבחון קשב וריכוז, לאחר השלמת שאלוני ההורים והמורה.',
    step1: 'בוחרים יום', step2: 'בוחרים שעה', step3: 'פרטי ההזמנה', available: 'השעות הפנויות', timezone: 'כל השעות לפי שעון ישראל',
    loading: 'בודקים שעות פנויות…', unavailable: 'הזמנת התורים באינטרנט אינה זמינה כרגע. אפשר לתאם עם המזכירות בטלפון.', empty: 'אין כרגע שעות פנויות בתקופה המוצגת. אפשר לפנות למזכירות.',
    retry: 'בדיקה מחדש', previous: 'חודש קודם', next: 'חודש הבא', chooseDay: 'בחרו יום בלוח כדי לראות שעות פנויות.',
    child: 'שם מלא של הילד/ה', parent: 'שם ההורה', phone: 'טלפון לחזרה', submit: 'אישור וקביעת התור', submitting: 'מאשרים את התור…',
    consent: 'אני ההורה או האפוטרופוס, ומאשר/ת שמירת פרטי ההזמנה לצורך תיאום התור.', noMedical: 'אין צורך להזין מידע רפואי או מספר זהות.',
    intake: 'קישור השאלון האישי שקיבלתם מהמכון', intakeHint: 'הדביקו את הקישור לשאלון ההורה. נדרשת השלמת שאלון ההורה ושאלון המורה לפני קביעת האבחון.',
    newFamily: 'עדיין אין תיק אבחון?', register: 'פתיחת תיק ושאלונים', confirmed: 'התור נקבע בהצלחה', saved: 'התור נשמר ביומן המרפאה שבחרתם.', reference: 'מספר הזמנה',
    address: 'תופיק זיאד 21, שפרעם', change: 'לשינוי או ביטול התור, פנו למזכירות וציינו את מספר ההזמנה.', contact: 'עזרה מהמזכירות', another: 'לאתר המכון',
    errors: {
      slot_taken: 'השעה כבר אינה פנויה. בחרו שעה אחרת.', invalid_slot: 'השעה אינה זמינה להזמנה. עדכנו את לוח התורים.',
      invalid_body: 'בדקו שמילאתם את הפרטים בצורה תקינה.', invalid_intake: 'קישור השאלון אינו תקין או שפג תוקפו. פנו למכון לקבלת קישור אישי.',
      intake_incomplete: 'יש להשלים את שאלון ההורה ושאלון המורה לפני קביעת האבחון.', already_booked: 'כבר קיימת הזמנה לתיק הזה. לשינוי התור פנו למזכירות.',
      rate_limited: 'הגעתם למספר ההזמנות האפשרי כרגע. לתיאום נוסף פנו למזכירות.', invalid_retry: 'פרטי הבקשה השתנו. פנו למזכירות כדי לבדוק אם התור נקבע.',
      processing: 'עדיין לא התקבל אישור סופי. המתינו שתי דקות ולחצו שוב על אישור, או פנו למזכירות. אין לפתוח הזמנה נוספת.',
      unavailable: 'לא ניתן לאשר את התור כרגע. פנו למזכירות או נסו שוב בהמשך.',
    },
  },
  ar: {
    cancelLink: 'رابط شخصي لإلغاء الموعد', keepCancel: 'احفظوا الرابط الشخصي للإلغاء لاحقًا. لا تشاركوه مع الآخرين.', reminderConsent: 'أوافق على تلقي تذكير عبر واتساب لهذا الرقم قبل الموعد بحوالي نصف ساعة.',
    institute: 'معهد أطفال السحر', doctor: 'د. بسيم نموز', home: 'موقع المعهد', language: 'اللغة',
    clinicPhone: 'هاتف عيادة الأطفال', clinicSecretary: 'السكرتيرة خلال ساعات عمل العيادة',
    pediatrics: 'عيادة طب الأطفال', adhd: 'عيادة الانتباه والتركيز', heading: 'احجزوا موعدًا بكل سهولة.',
    intro: 'اختاروا اليوم والساعة المناسبين. يُسجَّل الموعد في تقويم العيادة التي اخترتموها بعد تأكيد الحجز.',
    pedsIntro: 'احجزوا مباشرة في موعد متاح دون موافقة السكرتارية. يمكن الإلغاء عبر الرابط الشخصي بعد الحجز.', adhdIntro: 'حجز موعد لتشخيص اضطراب الانتباه والتركيز بعد استكمال استبيانات الأهل والمعلم.',
    step1: 'اختيار اليوم', step2: 'اختيار الساعة', step3: 'تفاصيل الحجز', available: 'المواعيد المتاحة', timezone: 'جميع الأوقات حسب توقيت إسرائيل',
    loading: 'جارٍ التحقق من المواعيد المتاحة…', unavailable: 'الحجز عبر الإنترنت غير متاح حاليًا. يمكن تنسيق موعد مع السكرتارية هاتفيًا.', empty: 'لا توجد مواعيد متاحة حاليًا في الفترة المعروضة. يمكن التواصل مع السكرتارية.',
    retry: 'التحقق مجددًا', previous: 'الشهر السابق', next: 'الشهر التالي', chooseDay: 'اختاروا يومًا من التقويم لعرض الساعات المتاحة.',
    child: 'الاسم الكامل للطفل/ة', parent: 'اسم ولي الأمر', phone: 'رقم الهاتف للتواصل', submit: 'تأكيد وحجز الموعد', submitting: 'جارٍ تأكيد الموعد…',
    consent: 'أنا ولي الأمر أو الوصي، وأوافق على حفظ تفاصيل الحجز لتنسيق الموعد.', noMedical: 'لا حاجة لإدخال معلومات طبية أو رقم هوية.',
    intake: 'رابط استبيان الأهل الشخصي الذي وصلكم من المعهد', intakeHint: 'الصقوا رابط استبيان الأهل. يجب استكمال استبيان الأهل واستبيان المعلم قبل حجز موعد التشخيص.',
    newFamily: 'لم تفتحوا ملف تشخيص بعد؟', register: 'فتح ملف واستبيانات', confirmed: 'تم حجز الموعد بنجاح', saved: 'تم تسجيل الموعد في تقويم العيادة التي اخترتموها.', reference: 'رقم الحجز',
    address: 'توفيق زياد 21، شفاعمرو', change: 'لتغيير الموعد أو إلغائه، تواصلوا مع السكرتارية واذكروا رقم الحجز.', contact: 'مساعدة من السكرتارية', another: 'موقع المعهد',
    errors: {
      slot_taken: 'لم يعد هذا الموعد متاحًا. اختاروا ساعة أخرى.', invalid_slot: 'هذا الموعد غير متاح للحجز. حدّثوا التقويم.',
      invalid_body: 'يرجى التأكد من صحة التفاصيل المدخلة.', invalid_intake: 'رابط الاستبيان غير صالح أو انتهت صلاحيته. تواصلوا مع المعهد للحصول على رابط شخصي.',
      intake_incomplete: 'يجب استكمال استبيان الأهل واستبيان المعلم قبل حجز موعد التشخيص.', already_booked: 'يوجد حجز لهذا الملف بالفعل. لتغييره، تواصلوا مع السكرتارية.',
      rate_limited: 'وصلتم إلى عدد الحجوزات المتاح حاليًا. تواصلوا مع السكرتارية لتنسيق موعد إضافي.', invalid_retry: 'تغيّرت تفاصيل الطلب. تواصلوا مع السكرتارية للتحقق من الحجز.',
      processing: 'لم يصل التأكيد النهائي بعد. انتظروا دقيقتين ثم اضغطوا على التأكيد مجددًا، أو تواصلوا مع السكرتارية. لا تفتحوا طلب حجز آخر.',
      unavailable: 'يتعذّر تأكيد الموعد حاليًا. تواصلوا مع السكرتارية أو حاولوا لاحقًا.',
    },
  },
  en: {
    cancelLink: 'Personal cancellation link', keepCancel: 'Save this personal link to cancel later. Do not share it with others.', reminderConsent: 'I agree to receive a WhatsApp reminder at this number about 30 minutes before my visit.',
    institute: 'Magic Kids Institute', doctor: 'Dr. Basim Namouz', home: 'Institute website', language: 'Language',
    clinicPhone: 'Pediatrics clinic phone', clinicSecretary: 'Secretary during clinic opening hours',
    pediatrics: 'Pediatrics clinic', adhd: 'ADHD clinic', heading: 'Your next visit, made simple.',
    intro: 'Choose a day and time. Once confirmed, your appointment is saved in the calendar of the clinic you selected.',
    pedsIntro: 'Book an available time directly, without secretary approval. Cancel later using your personal link.', adhdIntro: 'Book an ADHD assessment after completing the parent and teacher questionnaires.',
    step1: 'Choose a day', step2: 'Choose a time', step3: 'Booking details', available: 'Available appointments', timezone: 'All times are in Israel time',
    loading: 'Checking available appointments…', unavailable: 'Online booking is currently unavailable. Please call the clinic to arrange an appointment.', empty: 'There are no available appointments in this period. Please contact the clinic.',
    retry: 'Check again', previous: 'Previous month', next: 'Next month', chooseDay: 'Choose a day in the calendar to see available times.',
    child: 'Child’s full name', parent: 'Parent’s name', phone: 'Callback phone number', submit: 'Confirm and book', submitting: 'Confirming your appointment…',
    consent: 'I am the parent or guardian and agree to the booking details being stored to arrange this appointment.', noMedical: 'No medical information or ID number is needed.',
    intake: 'Your personal parent questionnaire link', intakeHint: 'Paste your parent questionnaire link. Both parent and teacher questionnaires must be complete before booking an assessment.',
    newFamily: 'New to the assessment service?', register: 'Start intake and questionnaires', confirmed: 'Your appointment is confirmed', saved: 'Your appointment has been saved in your selected clinic’s calendar.', reference: 'Booking reference',
    address: '21 Tawfiq Ziad St., Shefa-Amr', change: 'To change or cancel, contact the clinic and quote your booking reference.', contact: 'Contact the clinic', another: 'Institute website',
    errors: {
      slot_taken: 'That time is no longer available. Please choose another.', invalid_slot: 'That time is unavailable. Refresh the calendar.',
      invalid_body: 'Please check your details.', invalid_intake: 'Your questionnaire link is invalid or expired. Contact the institute for a personal link.',
      intake_incomplete: 'Both parent and teacher questionnaires must be completed before booking an assessment.', already_booked: 'This case already has a booking. Contact the clinic to change it.',
      rate_limited: 'The booking limit has been reached. Contact the clinic for additional appointments.', invalid_retry: 'The request details changed. Contact the clinic to check whether the appointment was booked.',
      processing: 'Final confirmation has not arrived. Wait two minutes and confirm again, or contact the clinic. Please do not create another booking.',
      unavailable: 'We cannot confirm this appointment right now. Contact the clinic or try again later.',
    },
  },
};
export type BookingLanguage = keyof typeof bookingCopy;
