'use client';
import { useRef, useState, type FormEvent } from 'react';
import { labels, treatments } from '@/lib/treatments/schema';
import styles from '@/components/booking/booking.module.css';
const copy = {
 he: {title:'פנייה לטיפול במכון',intro:'בחרו את סוג הטיפול והשאירו פרטים. הצוות יתאם איתכם תור לפי סדר הפניות, התאמה לטיפול וזמינות המטפל/ת. שליחת הטופס אינה קביעת תור.',patient:'שם הילד/ה',contact:'שם ההורה',phone:'טלפון נייד',type:'סוג הטיפול המבוקש',availability:'ימים ושעות שנוחים לכם (רשות)',privacy:'אין להזין מידע רפואי, אבחנות או מספר זהות.',consent:'אני ההורה או האפוטרופוס ומאשר/ת שמירת הפרטים במכון וחזרה אליי לתיאום.',submit:'שליחת פנייה למכון',sending:'שולחים…',done:'הפנייה התקבלה במכון. הצוות יחזור אליכם לתיאום.',error:'לא התקבל אישור. אפשר לנסות שוב עם אותם פרטים או לפנות למכון.',links:'לאבחון קשב יש לפתוח תיק ולהשלים שאלוני הורים ומורה. לבדיקת MOXO נדרש אישור המכון.',adhd:'פתיחת תיק קשב',moxo:'בקשת MOXO',home:'חזרה לאתר'},
 ar: {title:'طلب علاج في المعهد',intro:'اختاروا نوع العلاج واتركوا بياناتكم. ينسّق الفريق الموعد حسب ترتيب الطلبات، ملاءمة العلاج وتوفر المعالج/ة. إرسال النموذج لا يُعد حجزًا.',patient:'اسم الطفل/ة',contact:'اسم ولي الأمر',phone:'رقم الهاتف المحمول',type:'نوع العلاج المطلوب',availability:'الأيام والساعات المناسبة (اختياري)',privacy:'لا تدخلوا معلومات طبية أو تشخيصات أو رقم هوية.',consent:'أنا ولي الأمر أو الوصي وأوافق على حفظ التفاصيل في المعهد والتواصل معي للتنسيق.',submit:'إرسال الطلب للمعهد',sending:'جارٍ الإرسال…',done:'استلم المعهد طلبكم. سيتواصل الفريق معكم لتنسيق الموعد.',error:'لم يصل التأكيد. حاولوا مجددًا بنفس التفاصيل أو تواصلوا مع المعهد.',links:'لتشخيص الانتباه يجب فتح ملف واستكمال استبيانات الأهل والمعلم. فحص MOXO يتطلب موافقة المعهد.',adhd:'فتح ملف الانتباه',moxo:'طلب MOXO',home:'العودة للموقع'},
 en: {title:'Request institute treatment',intro:'Choose a treatment and leave your details. Our team schedules by request order, treatment fit and therapist availability. Submitting this form does not book an appointment.',patient:'Child’s name',contact:'Parent’s name',phone:'Mobile phone',type:'Requested treatment',availability:'Preferred days and times (optional)',privacy:'Do not include medical details, diagnoses or ID numbers.',consent:'I am the parent or guardian and agree to the institute storing these details and contacting me to arrange care.',submit:'Send request',sending:'Sending…',done:'The institute received your request. The team will contact you to arrange an appointment.',error:'Confirmation was not received. Retry with the same details or contact the institute.',links:'ADHD assessments require intake and completed parent and teacher questionnaires. MOXO requires institute approval.',adhd:'Start ADHD intake',moxo:'Request MOXO',home:'Back to website'},
};
export default function RequestForm({language, initialTreatment}: {language:keyof typeof copy;initialTreatment:string}) {
 const t=copy[language]; const id=useRef(''); const retry=useRef<Record<string,unknown>|null>(null);
 const [state,setState]=useState('idle');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fields=new FormData(e.currentTarget);if(!id.current)id.current=crypto.randomUUID();
 const body=retry.current??{id:id.current,patient:fields.get('patient'),contact:fields.get('contact'),phone:fields.get('phone'),treatment:fields.get('treatment'),availability:fields.get('availability'),language,consent:fields.get('consent')==='on',website:fields.get('website')};retry.current=body;setState('sending');
 try{const response=await fetch('/api/treatments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok||!data.received){if(response.status<500){retry.current=null;id.current='';}throw new Error();}setState('done');}catch{setState('error');}}
 return <div className={styles.page} lang={language} dir={language==='en'?'ltr':'rtl'}><header className={styles.header}><a className={styles.brand} href={`https://magickidsinstitute.com/index.html?lang=${language}`}><img src="https://magickidsinstitute.com/assets/institute-logo.jpg" width="56" height="56" alt="Magic Kids Institute"/>MAGIC KIDS INSTITUTE</a><nav className={styles.languages}>{(['ar','he','en'] as const).map(l=><a key={l} href={`/treatments?lang=${l}`}>{l==='ar'?'العربية':l==='he'?'עברית':'English'}</a>)}</nav></header><main className={styles.panel} style={{maxWidth:760,margin:'24px auto'}}><h1>{t.title}</h1><p>{t.intro}</p>{state==='done'?<div role="status"><h2>{t.done}</h2><code>{id.current}</code></div>:<form onSubmit={submit}><fieldset className={styles.fields} disabled={state==='sending'||(state==='error'&&!!retry.current)}><label>{t.type}<select name="treatment" defaultValue={treatments.includes(initialTreatment as typeof treatments[number])?initialTreatment:'other'}>{treatments.map((v,i)=><option key={v} value={v}>{labels[language][i]}</option>)}</select></label><label>{t.patient}<input name="patient" required minLength={2} maxLength={100}/></label><label>{t.contact}<input name="contact" required minLength={2} maxLength={100} autoComplete="name"/></label><label>{t.phone}<input name="phone" type="tel" dir="ltr" autoComplete="tel" required maxLength={25}/></label><label>{t.availability}<textarea name="availability" maxLength={300}/></label><p>{t.privacy}</p><div className={styles.honeypot} aria-hidden="true"><input name="website" tabIndex={-1} autoComplete="off"/></div><label className={styles.consent}><input name="consent" type="checkbox" required/>{t.consent}</label></fieldset>{state==='error'&&<p role="alert">{t.error}</p>}<button className={styles.primary} disabled={state==='sending'}>{state==='sending'?t.sending:t.submit}</button></form>}<p>{t.links}</p><p><a href={`/onboarding/public?lang=${language}`}>{t.adhd}</a> · <a href={`/moxo?lang=${language}`}>{t.moxo}</a></p><a href={`https://magickidsinstitute.com/index.html?lang=${language}`}>{t.home}</a></main></div>;
}
