'use client';
import {useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {localToUTC} from '@/lib/booking/schedule';
export default function StaffActions({id,status}:{id:string;status:string}){
 const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function send(body:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch('/api/admin/treatments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...body})});const data=await r.json();if(!r.ok){setError(data.error==='slot_taken'?'למטפל/ת כבר נקבע טיפול בשעה זו.':'לא ניתן לשמור. רעננו ובדקו את הבקשה.');return;}router.refresh();}catch{setError('לא התקבל אישור שמירה. ניתן לנסות שוב.');}finally{setBusy(false);}}
 function schedule(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const [date,time]=String(f.get('start')).split('T'),[h,m]=time.split(':').map(Number);void send({action:'schedule',start:localToUTC(date,h*60+m).toISOString(),duration:Number(f.get('duration')),therapist:String(f.get('therapist')),availabilityVerified:f.get('verified')==='on'});}
 return <div className="space-y-3">{status!=='scheduled'&&status!=='closed'&&<><button disabled={busy} className="btn-secondary" onClick={()=>send({action:'contacted'})}>סימון: נוצר קשר</button><form onSubmit={schedule} className="flex flex-wrap gap-3 items-end"><label>מטפל/ת<input name="therapist" required minLength={2} maxLength={100} className="input" disabled={busy}/></label><label>מועד לפי שעון ישראל<input type="datetime-local" name="start" required className="input" disabled={busy}/></label><label>משך בדקות<input type="number" name="duration" min={15} max={180} defaultValue={60} required className="input" disabled={busy}/></label><label className="flex gap-2"><input type="checkbox" name="verified" required disabled={busy}/>תיאמתי עם ההורה ובדקתי זמינות מטפל/ת וחדר</label><button className="btn-primary" disabled={busy}>שמירת תור במערכת המכון</button></form></>}{status!=='closed'&&<button className="text-red-700 underline" disabled={busy} onClick={()=>{if(window.confirm('לסגור את הפנייה ולבטל את השיבוץ שלה, אם קיים?'))void send({action:'closed'});}}>סגירת פנייה / ביטול השיבוץ</button>}{error&&<p role="alert" className="text-red-700">{error}</p>}</div>;
}
